// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4GrZTJSTGBjO7mKYmfYCiCFvOQj_-jWM',
    appId: '1:135184268289:web:8acdf9fca68a0f6a1e5400',
    messagingSenderId: '135184268289',
    projectId: 'insidehome-c5f1d',
    authDomain: 'insidehome-c5f1d.firebaseapp.com',
    databaseURL: 'https://insidehome-c5f1d-default-rtdb.firebaseio.com',
    storageBucket: 'insidehome-c5f1d.appspot.com',
    measurementId: 'G-RDBR72FZ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlfnWY2vqZ9ANgDxGfouEuAxnpdyqoN1g',
    appId: '1:135184268289:android:19d9ee5a28aea0ac1e5400',
    messagingSenderId: '135184268289',
    projectId: 'insidehome-c5f1d',
    databaseURL: 'https://insidehome-c5f1d-default-rtdb.firebaseio.com',
    storageBucket: 'insidehome-c5f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJ443PNgdux5mC2_9YmwfxQNrOoWGiOg',
    appId: '1:135184268289:ios:8c0ed93812ff7b201e5400',
    messagingSenderId: '135184268289',
    projectId: 'insidehome-c5f1d',
    databaseURL: 'https://insidehome-c5f1d-default-rtdb.firebaseio.com',
    storageBucket: 'insidehome-c5f1d.appspot.com',
    iosClientId:
        '135184268289-a41fpalkl05k8tbsmeqgcgchnpp56pgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fadba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJ443PNgdux5mC2_9YmwfxQNrOoWGiOg',
    appId: '1:135184268289:ios:8e2407b8fd9dc1161e5400',
    messagingSenderId: '135184268289',
    projectId: 'insidehome-c5f1d',
    databaseURL: 'https://insidehome-c5f1d-default-rtdb.firebaseio.com',
    storageBucket: 'insidehome-c5f1d.appspot.com',
    iosClientId:
        '135184268289-4g004vdjvas291asn1o7aa2478uadt41.apps.googleusercontent.com',
    iosBundleId: 'Y',
  );
}
